name: Auto Merge PR at 3:00 AM

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3:00 AM every day

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto Merge PR
        id: auto-merge
        uses: pascalgn/automerge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: merge  
          merge_filter: 'label=auto-merge'  

      - name: Check for conflicts
        if: steps.auto-merge.outputs.result == 'conflict'
        run: echo "PR has conflicts, cannot merge"
